apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: stress-ng
        image: polinux/stress-ng
        command: ["/bin/sleep", "3600"]
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
